Implement rimraf
ASU-CodeDevils/CD-Library pull request #10
Opened 2022-09-09 22:07 UTC by frankjlin16

Replaces `rm` from build script with `rimraf`.

2022-09-09 22:10 UTC, reharri7 commented
Was this the issue building between windows and unix? @frankjlin16

2022-09-09 22:13 UTC, reharri7 commented
From the npm package it seems sound and would fix the issue. @frankjlin16 I am not the project lead, but this does seem sound to me. I will be handing this off to @KevinThePepper :)

2022-09-10 15:02 UTC, KevinThePepper requested changes
@frankjlin16 can you scope this change to the `@cd/ui` library? So instead of installing using yarn:
```
yarn add rimraf
```
Do it with Lerna:

```
npx lerna add rimraf --scope=@cd/ui
```

2022-09-10 16:14 UTC, KevinThePepper approved these changes

2022-09-10 16:14 UTC, merged